- name: Send Telegram message
  env:
    TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    REPO: ${{ github.repository }}
    ACTOR: ${{ github.actor }}
    PR_NUM: ${{ github.event.pull_request.number }}
    PR_TITLE: ${{ github.event.pull_request.title }}
    PR_URL: ${{ github.event.pull_request.html_url }}
    BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
    HEAD_BRANCH: ${{ github.event.pull_request.head.ref }}
  run: |
    set -euo pipefail

    API_URL="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"

    # Build the message with real newlines; curl will encode it.
    MSG="\<b\>New Pull Request\</b\>
Repo: \<code\>${REPO}\</code\>
By: \<b\>${ACTOR}\</b\>
PR: \<b\>#${PR_NUM}\</b\> — ${PR_TITLE}
Branch: \<code\>${HEAD_BRANCH}\</code\> → \<code\>${BASE_BRANCH}\</code\>
Link: ${PR_URL}"

    # Send (let curl do the encoding for 'text')
    curl -sS --fail "${API_URL}" \
      -d "chat_id=${CHAT_ID}" \
      -d "parse_mode=HTML" \
      -d "disable_web_page_preview=true" \
      --data-urlencode "text=${MSG}"
